name: galaxy_animation
description: "The Galaxy Animation Flutter package provides an engaging way to display an animated galaxy-like structure in your Flutter applications."
version: 0.0.1
homepage: https://github.com/therasuldev/galaxy-animation

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: